-- 添加用户个人资料字段
-- 体重、年龄、性别

ALTER TABLE users ADD COLUMN IF NOT EXISTS weight DECIMAL(5,2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20);

